"""add paper trading tables

Revision ID: 28868836ba60
Revises: c47475b45b3f
Create Date: 2026-03-11 20:09:09.289670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28868836ba60'
down_revision: Union[str, Sequence[str], None] = 'c47475b45b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('outcome_pnl_pct', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('outcome_grade', sa.String(length=1), nullable=True))
    op.add_column('signals', sa.Column('outcome_exit_price', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('outcome_graded_at', sa.DateTime(), nullable=True))
    op.add_column('signals', sa.Column('volume_ratio', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('atr_ratio', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('market_regime', sa.String(length=30), nullable=True))
    op.add_column('signals', sa.Column('reward_risk_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'reward_risk_ratio')
    op.drop_column('signals', 'market_regime')
    op.drop_column('signals', 'atr_ratio')
    op.drop_column('signals', 'volume_ratio')
    op.drop_column('signals', 'outcome_graded_at')
    op.drop_column('signals', 'outcome_exit_price')
    op.drop_column('signals', 'outcome_grade')
    op.drop_column('signals', 'outcome_pnl_pct')
    # ### end Alembic commands ###
