"""Add recommendation_date to signals

Revision ID: c47475b45b3f
Revises: 
Create Date: 2026-01-17 16:22:39.223201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47475b45b3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'signal_outcomes', 'signals', ['signal_id'], ['id'])
    op.add_column('signals', sa.Column('recommendation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'recommendation_date')
    op.drop_constraint(None, 'signal_outcomes', type_='foreignkey')
    # ### end Alembic commands ###
